name : CI Pipeline

on : 
  push :
    branches : [ main ]

jobs : 
  build : 
    runs-on : ubuntu-latest 

    stpes:
      - name : Checkout Code
        uses : actions/checkout@v5

      - name : Setup Node.js
        uses : actions/setup-node@v4
        with :
          node-version : '20'

      - name : Install Dependencies
        run : npm install

      - name : Run Tests
        run : npm test